SELECT * FROM DARBUOTOJAI;
SELECT GIMIMO_DATA FROM DARBUOTOJAI;
SELECT VARDAS, PAVARDĖ, PAREIGOS FROM DARBUOTOJAI;
SELECT DISTINCT SKYRIUS_PAVADINIMAS FROM DARBUOTOJAI;
SELECT * FROM DARBUOTOJAI WHERE SKYRIUS_PAVADINIMAS="Gamybos";
SELECT * FROM DARBUOTOJAI WHERE VARDAS="Giedrius";
SELECT * FROM DARBUOTOJAI WHERE GIMIMO_DATA="1986-09-19";
SELECT * FROM DARBUOTOJAI WHERE PAVARDĖ="Sabutis";
SELECT VARDAS, PAVARDĖ FROM DARBUOTOJAI 
WHERE SKYRIUS_PAVADINIMAS="Gamybos" AND PAREIGOS="Programuotojas";

INSERT INTO DARBUOTOJAI VALUES(
"Marius", "Lietis", "1991-02-12", " ", " ");

UPDATE DARBUOTOJAI SET PAREIGOS="Duomenų analitikas" 
WHERE PAVARDĖ ="Lietis";

UPDATE DARBUOTOJAI SET SKYRIUS_PAVADINIMAS="Pardavimų" 
WHERE PAVARDĖ ="Lietis";

DELETE FROM DARBUOTOJAI WHERE PAVARDĖ = "Lietis";

INSERT INTO DARBUOTOJAI VALUES(
"Marius", "Antanaitis ", "1981-06-09", "Programuotojas", "Finansų");

INSERT INTO DARBUOTOJAI VALUES(
"Marius", "Antanaitis ", "1981-06-09", "Programuotojas", "Pardavimų");

DELETE FROM DARBUOTOJAI WHERE PAVARDĖ = "Antanaitis" AND VARDAS="Marius";

--UPDATE DARBUOTOJAI SET PAREIGOS="Testuotojas" WHERE VARDAS="Marius" PAVARDĖ ="Lietis" AND VARDAS="Marius" PAVARDĖ ="Lietis";

--SELECT PAREIGOS FROM DARBUOTOJAI WHERE PAREIGOS="Testuotojas" AND COUNT;

