SELECT VARDAS, PAVARDĖ, ASMENS_KODAS 
FROM DARBUOTOJAS WHERE ASMENS_KODAS 
LIKE"%880720%";

SELECT ASMENS_KODAS, DIRBA_NUO
FROM DARBUOTOJAS WHERE DIRBA_NUO 
BETWEEN "2009-10-30" AND "2012-11-30";

SELECT VARDAS, SKYRIUS_ID, PROJEKTAS_ID 
FROM DARBUOTOJAS WHERE SKYRIUS_ID IN (2, 3);

SELECT VARDAS, PAVARDĖ, ASMENS_KODAS 
FROM DARBUOTOJAS WHERE ASMENS_KODAS 
LIKE"4%" OR ASMENS_KODAS LIKE"6%";

SELECT * FROM DARBUOTOJAS WHERE ASMENS_KODAS 
LIKE"_____12%";

--6 

SELECT * FROM DARBUOTOJAS 
WHERE PAREIGOS IS NULL;

SELECT VARDAS, PAVARDĖ, PAREIGOS, DIRBA_NUO
FROM DARBUOTOJAS WHERE DIRBA_NUO >= "2011-02-12" 
AND PAREIGOS="Programuotojas";

SELECT VARDAS, PAVARDĖ, SKYRIUS_ID, PROJEKTAS_ID 
FROM DARBUOTOJAS WHERE SKYRIUS_ID=2 
OR PROJEKTAS_ID=1;

SELECT VARDAS FROM DARBUOTOJAS 
WHERE VARDAS NOT LIKE"A%";

SELECT VARDAS, PAVARDĖ, DIRBA_NUO
FROM DARBUOTOJAS ORDER BY DIRBA_NUO;

SELECT VARDAS, PAVARDĖ, DIRBA_NUO
FROM DARBUOTOJAS ORDER BY DIRBA_NUO DESC;

SELECT MIN(PROJEKTAS_ID), MAX(PROJEKTAS_ID) FROM DARBUOTOJAS;

SELECT PROJEKTAS_ID, count(*) 
FROM DARBUOTOJAS 
GROUP BY PROJEKTAS_ID 
ORDER BY count(*) DESC;

SELECT PROJEKTAS_ID, count(*) 
FROM DARBUOTOJAS 
GROUP BY PROJEKTAS_ID 
HAVING count(*) > 3
ORDER BY count(*) DESC;

--16
