--1
SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, PROJEKTAS.PAVADINIMAS
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON DARBUOTOJAS.PROJEKTAS_ID=PROJEKTAS.ID

--2
SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, PROJEKTAS.PAVADINIMAS
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON DARBUOTOJAS.PROJEKTAS_ID=PROJEKTAS.ID
WHERE PAVADINIMAS="Galerija"

--3
SELECT VARDAS, PAVARDĖ, PROJEKTAS.PAVADINIMAS, SKYRIUS.PAVADINIMAS
FROM DARBUOTOJAS, PROJEKTAS, SKYRIUS
WHERE DARBUOTOJAS.PROJEKTAS_ID=PROJEKTAS.ID 
AND DARBUOTOJAS.SKYRIUS_ID=SKYRIUS.ID 
AND PROJEKTAS.PAVADINIMAS="Projektų valdymas" 
AND SKYRIUS.PAVADINIMAS="Pardavimų"

--4
SELECT VARDAS, PAVARDĖ, PROJEKTAS.PAVADINIMAS
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON DARBUOTOJAS.PROJEKTAS_ID=PROJEKTAS.ID 
WHERE ASMENS_KODAS LIKE"4%" AND PAVADINIMAS="Projektų valdymas"
OR ASMENS_KODAS LIKE"6%" AND PAVADINIMAS="Projektų valdymas"

--5
SELECT SKYRIUS.PAVADINIMAS, COUNT()
FROM DARBUOTOJAS
JOIN SKYRIUS
ON DARBUOTOJAS.SKYRIUS_ID = SKYRIUS.ID
GROUP BY SKYRIUS.PAVADINIMAS

--6
SELECT SKYRIUS.PAVADINIMAS, COUNT()
FROM DARBUOTOJAS
JOIN SKYRIUS
ON DARBUOTOJAS.SKYRIUS_ID = SKYRIUS.ID
GROUP BY SKYRIUS.PAVADINIMAS
HAVING COUNT() > 5

--7
SELECT VARDAS, PAVARDĖ, PAREIGOS, SKYRIUS.PAVADINIMAS
FROM DARBUOTOJAS
JOIN SKYRIUS
ON DARBUOTOJAS.SKYRIUS_ID=SKYRIUS.ID
WHERE PAREIGOS IS NOT "Vadovas"

--8 
INSERT INTO DARBUOTOJAS VALUES(
"21", "Pranas", "Logis", "38807117896", NULL, "2009-11-12", NULL, NULL, NULL, NULL
);

--9 
SELECT DARBUOTOJAS.VARDAS, DARBUOTOJAS.PAVARDĖ, SKYRIUS.PAVADINIMAS
FROM DARBUOTOJAS
LEFT JOIN SKYRIUS
ON DARBUOTOJAS.SKYRIUS_ID=SKYRIUS.ID

--10
SELECT PROJEKTAS.PAVADINIMAS, COUNT()
FROM DARBUOTOJAS
JOIN PROJEKTAS
ON DARBUOTOJAS.PROJEKTAS_ID=PROJEKTAS.ID
GROUP BY PROJEKTAS.PAVADINIMAS
HAVING COUNT() > 4

--11

